export const LOAD_BOARDS = "LOAD_BOARDS";
export const LOAD_BOARDS_ERROR = "LOAD_BOARDS_ERROR";
export const ADD_BOARDS = "ADD_BOARDS";
export const SET_CARDS_LOADED = "SET_CARDS_LOADED";
export const LOAD_CARDS_FOR_BOARD_ERROR = "LOAD_CARDS_FOR_BOARD_ERROR";
