export const ADD_ITEMS = "ADD_ITEMS";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const CREATE_ITEM_REQUEST = "CREATE_ITEM_REQUEST";
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const CREATE_ITEM_FAILURE = "CREATE_ITEM_FAILURE";

export const READ_ITEMS_REQUEST = "READ_ITEMS_REQUEST";
export const READ_ITEMS_SUCCESS = "READ_ITEMS_SUCCESS";
export const READ_ITEMS_FAILURE = "READ_ITEMS_FAILURE";

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE";

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE";
