export const REDIRECT_TO_API_FOR_GET_TOKEN = "REDIRECT_TO_API_FOR_GET_TOKEN";
export const LOGIN_BY_TOKEN = "LOGIN_BY_TOKEN";
export const LOGIN_BY_TOKEN_SUCCESS = "LOGIN_BY_TOKEN_SUCCESS";
export const LOGOUT_BY_TOKEN = "LOGOUT_BY_TOKEN";
